
services:
  lulifa-nginx:
    image: nginx:1.28.0-alpine
    hostname: lulifa-nginx
    container_name: lulifa-nginx
    ports:
      - "80:80"
      - "443:443"
    privileged: true
    volumes:
      - ./deploy/middleware/nginx/conf.d:/etc/nginx/conf.d
      - ./deploy/middleware/nginx/logs:/var/log/nginx
      - ./deploy/middleware/nginx/certs:/etc/nginx/certs:ro
      - ./apps/admin/frontend/dist:/usr/share/nginx/html/admin
    restart: always
    networks:
      - lulifa-next-admin
  lulifa-mysql:
    image: mysql:8.0
    hostname: lulifa-mysql
    container_name: lulifa-mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_ROOT_HOST=${MYSQL_ROOT_HOST}
      - TZ=${TZ}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./deploy/middleware/mysql/conf:/etc/mysql/conf.d
      - ./deploy/middleware/mysql/logs:/logs
    restart: always
    networks:
      - lulifa-next-admin

  lulifa-redis:
    image: redis:6
    hostname: lulifa-redis
    container_name: lulifa-redis
    environment:
     - TZ=${TZ}
    volumes:
      - redis_data:/data
      - ./deploy/middleware/redis/conf:/usr/local/etc/redis
      - ./deploy/middleware/redis/logs:/logs
    ports:
      - "6379:6379"
    restart: always
    networks:
      - lulifa-next-admin
  
  lulifa-rabbitmq:
    image: rabbitmq:3.12-management
    hostname: lulifa-rabbitmq
    container_name: lulifa-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
      - "25672:25672"
      - "1883:1883"
    environment:
      - RABBITMQ_ERLANG_COOKIE=${RABBITMQ_ERLANG_COOKIE}
      - RABBITMQ_DEFAULT_VHOST=${RABBITMQ_DEFAULT_VHOST}
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
      - TZ=${TZ}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - ./deploy/middleware/rabbitmq/conf:/etc/rabbitmq
      - rabbitmq_logs:/var/log/rabbitmq
    restart: always
    networks:
      - lulifa-next-admin

  lulifa-tdengine:
    image: tdengine/tdengine:3.3.6.9
    hostname: lulifa-tdengine
    container_name: lulifa-tdengine
    ports:
     - "6030:6030"
     - "6041:6041"
     - "6043:6043"
     - "6044-6049:6044-6049"
     - "6044-6045:6044-6045/udp"
     - "6060:6060"
    environment:
     - TZ=${TZ}
    volumes:
     - tdengine_data:/var/lib/taos
     - ./deploy/middleware/tdengine/conf:/etc/taos
     - ./deploy/middleware/tdengine/logs:/var/log/taos
    restart: always
    networks:
      - lulifa-next-admin
volumes:
  mysql_data:
  redis_data:
  rabbitmq_data:
  rabbitmq_logs:
  tdengine_data:

networks:
  lulifa-next-admin:
    name: lulifa-next-admin
    driver: bridge
