services:
  admin-api:
    environment:
      # App 基本配置
      - App__SslFile=openiddict.pfx
      - App__SslPassword=e1c48393-0c43-11f0-9582-4aecacda42db
      - App__ShowPii=true
      - App__SelfUrl=http://admin-api:30001/
      - App__CorsOrigins=http://www.lulifa.com:8080,http://www.lulifa.com:30001,http://www.lulifa.com

      # App Urls
      - App__Urls__Applications__MVC__RootUrl=http://admin-api:30001
      - App__Urls__Applications__MVC__Urls__Abp.Account.EmailConfirm=Account/EmailConfirm
      - App__Urls__Applications__MVC__Urls__Abp.Account.EmailVerifyLogin=Account/VerifyCode
      - App__Urls__Applications__STS__RootUrl=http://admin-api:30001
      - App__Urls__Applications__VuePureAdmin__RootUrl=http://admin-api:5666
      - App__Urls__Applications__VuePureAdmin__Urls__Abp.Account.EmailConfirm=account/email-confirm
      - App__Urls__Applications__VuePureAdmin__Urls__Abp.Account.EmailVerifyLogin=account/verify-code

      # Elasticsearch
      - Elasticsearch__NodeUris=http://lulifa-elasticsearch:9200

      # CAP 配置
      - CAP__IsEnabled=false
      - CAP__MySql__ConnectionString=Server=lulifa-mysql;Database=ruichen;User Id=root;Password=123456;SslMode=None
      - CAP__RabbitMQ__HostName=lulifa-rabbitmq
      - CAP__RabbitMQ__Port=5672
      - CAP__RabbitMQ__UserName=admin
      - CAP__RabbitMQ__Password=123456
      - CAP__RabbitMQ__ExchangeName=RuiChen.Abp.Application
      - CAP__RabbitMQ__VirtualHost=/
      - CAP__Redis__Configuration=lulifa-redis

      # 分布式缓存
      - DistributedCache__HideErrors=true
      - DistributedCache__KeyPrefix=RuiChen.Abp.Application

      # 分布式锁
      - DistributedLock__IsEnabled=true
      - DistributedLock__Redis__Configuration=lulifa-redis,defaultDatabase=14

      # Redis
      - Redis__IsEnabled=true
      - Redis__Configuration=lulifa-redis,defaultDatabase=15
      - Redis__InstanceName=RuiChen.Abp.Application

      # 功能验证缓存 Redis
      - Features__Validation__Redis__Configuration=lulifa-redis,defaultDatabase=13
      - Features__Validation__Redis__InstanceName=RuiChen.Abp.Application

      # 连接字符串
      - ConnectionStrings__Default=Server=lulifa-mysql;Database=ruichen;User Id=root;Password=123456

      # AuthServer 配置
      - AuthServer__Authority=http://www.lulifa.com:30001/
      - AuthServer__Audience=lingyun-abp-application
      - AuthServer__RequireHttpsMetadata=false
      - AuthServer__SwaggerClientId=vue-oauth-client
      - AuthServer__SwaggerClientSecret=1q2w3E*

      # OpenIddict 应用配置
      - OpenIddict__Applications__VueAdmin__ClientId=vue-admin-client
      - OpenIddict__Applications__VueAdmin__ClientSecret=1q2w3e*
      - OpenIddict__Applications__VueAdmin__RootUrl=http://www.lulifa.com:8080/
      - OpenIddict__Applications__VueOAuthClient__ClientId=vue-oauth-client
      - OpenIddict__Applications__VueOAuthClient__RootUrls__0=http://www.lulifa.com:8080/
      - OpenIddict__Applications__VueOAuthClient__RootUrls__1=http://www.lulifa.com:30001/

      # JSON 日期格式配置
      - Json__OutputDateTimeFormat=yyyy-MM-dd HH:mm:ss
      - Json__InputDateTimeFormats__0=yyyy-MM-dd HH:mm:ss
      - Json__InputDateTimeFormats__1=yyyy-MM-ddTHH:mm:ss

      # 加密配置
      - StringEncryption__DefaultPassPhrase=s46c5q55nxpeS8Ra
      - StringEncryption__InitVectorBytes=s83ng0abvd02js84
      - StringEncryption__DefaultSalt=sf&5)s3#

      # 审计配置
      - Auditing__AllEntitiesSelector=true
      - AuditLogging__IPLocation__IsEnabled=true
      - AuditLogging__Elasticsearch__IndexPrefix=abp.dev.auditing

      # 日志配置
      - Serilog__MinimumLevel__Default=Information
      - Serilog__MinimumLevel__Override__System=Warning
      - Serilog__MinimumLevel__Override__Microsoft=Warning
      - Serilog__MinimumLevel__Override__Microsoft.EntityFrameworkCore=Warning
      - Serilog__MinimumLevel__Override__DotNetCore=Warning
      - Serilog__WriteTo__1__Name=Elasticsearch
      - Serilog__WriteTo__1__Args__nodeUris=http://lulifa-elasticsearch:9200
      - Serilog__WriteTo__1__Args__indexFormat=abp.dev.logging-{0:yyyy.MM.dd}
      - Serilog__WriteTo__1__Args__autoRegisterTemplate=true
      - Serilog__WriteTo__1__Args__autoRegisterTemplateVersion=ESv7

      # 时间配置
      - Clock__Kind=Local

      # Forward 头配置
      - Forwarded__ForwardedHeaders=XForwardedFor,XForwardedProto

      # FeatureManagement / SettingManagement 等
      - FeatureManagement__IsDynamicStoreEnabled=true
      - SettingManagement__IsDynamicStoreEnabled=true
      - PermissionManagement__IsDynamicStoreEnabled=true
      - TextTemplating__IsDynamicStoreEnabled=true

