
services:
  lulifa-yesplay:
    image: fogforest/yesplaymusic:latest
    container_name: lulifa-yesplay
    expose:
      - "80"
    environment:
      - TZ=${TZ}
    restart: always
    networks:
      - lulifa-next-admin

  lulifa-libretv:
    image: bestzwei/libretv:latest
    container_name: lulifa-libretv
    expose:
      - "8080"
    environment:
      - TZ=${TZ}
      - PASSWORD=${LIBRETV_PASSWORD}
      - ADMINPASSWORD=${LIBRETV_ADMIN_PASSWORD}
    restart: always
    networks:
      - lulifa-next-admin
  
  lulifa-linux-command:
    image: wcjiang/linux-command:latest
    container_name: lulifa-linux-command
    expose:
      - "3000"
    environment:
      - TZ=${TZ}
    restart: always
    networks:
      - lulifa-next-admin

  lulifa-lychee:
    image: lycheeorg/lychee:latest
    container_name: lulifa-lychee
    restart: always
    environment:
      - TZ=${TZ}
      - APP_URL=http://www.photo.lulifa.com
      - APP_FORCE_HTTPS=false

      - DB_CONNECTION=mysql
      - DB_HOST=lulifa-mysql
      - DB_PORT=3306
      - DB_DATABASE=lychee
      - DB_USERNAME=root
      - DB_PASSWORD="Ruichen@20190217"
    expose:
      - "80"  # 通过80端口对外暴露
    volumes:
      - ./apps/lychee/uploads:/uploads
      - ./apps/lychee/conf:/conf
      - ./apps/lychee/logs:/logs
      - ./apps/lychee/sym:/sym
      - ./apps/lychee/tmp:/lychee-tmp
    networks:
      - lulifa-next-admin


networks:
  lulifa-next-admin:
    name: lulifa-next-admin
    driver: bridge