
services:

  lulifa-onenav:
    image: helloz/onenav
    container_name: lulifa-onenav
    restart: always
    environment:
      - TZ=${TZ}
    expose:
      - "80"
    volumes:
      - ./apps/onenav/data:/data/wwwroot/default/data
    networks:
      - lulifa-next-admin
  
  lulifa-yesplay:
    image: fogforest/yesplaymusic:latest
    container_name: lulifa-yesplay
    expose:
      - "80"
    environment:
      - TZ=${TZ}
    restart: always
    networks:
      - lulifa-next-admin

  lulifa-libretv:
    image: bestzwei/libretv:latest
    container_name: lulifa-libretv
    expose:
      - "8080"
    environment:
      - TZ=${TZ}
      - PASSWORD=${LIBRETV_PASSWORD}
      - ADMINPASSWORD=${LIBRETV_ADMIN_PASSWORD}
    restart: always
    networks:
      - lulifa-next-admin
  
  lulifa-linux-command:
    image: wcjiang/linux-command:latest
    container_name: lulifa-linux-command
    expose:
      - "3000"
    environment:
      - TZ=${TZ}
    restart: always
    networks:
      - lulifa-next-admin

  lulifa-lychee:
    image: lycheeorg/lychee:latest
    container_name: lulifa-lychee
    restart: always
    environment:
      - TZ=${TZ}
      - APP_URL=http://www.photo.lulifa.com
      - APP_FORCE_HTTPS=false

      - DB_CONNECTION=mysql
      - DB_HOST=lulifa-mysql
      - DB_PORT=3306
      - DB_DATABASE=lychee
      - DB_USERNAME=root
      - DB_PASSWORD="Ruichen@20190217"
    expose:
      - "80"
    volumes:
      - ./apps/lychee/uploads:/uploads
      - ./apps/lychee/conf:/conf
      - ./apps/lychee/logs:/logs
      - ./apps/lychee/sym:/sym
      - ./apps/lychee/tmp:/lychee-tmp
    networks:
      - lulifa-next-admin

  lulifa-talebook:
    image: talebook/talebook:latest
    container_name: lulifa-talebook
    restart: always
    environment:
      - TZ=${TZ}
    expose:
      - "80"
    volumes:
      - ./apps/talebook/data:/data
    networks:
      - lulifa-next-admin

  lulifa-newsnow:
    image: ghcr.io/ourongxing/newsnow:latest
    container_name: lulifa-newsnow
    restart: always
    expose:
      - "4444"
    environment:
      - TZ=${TZ}
      - HOST=0.0.0.0
      - PORT=4444
      - NODE_ENV=production
      - INIT_TABLE=true
      - ENABLE_CACHE=true
      - JWT_SECRET=Ruichen@20190217
      - G_CLIENT_ID=${NEWSNOW_CLIENT_ID}
      - G_CLIENT_SECRET=${NEWSNOW_CLIENT_SECRET}
    volumes:
      - ./apps/newsnow/data:/app/data
    networks:
      - lulifa-next-admin

  lulifa-etherpad:
    image: etherpad/etherpad:latest
    container_name: lulifa-etherpad
    environment:
      - ETH_PAD_DB=sqlite
      - TZ=${TZ}
    volumes:
      - etherpad_data:/opt/etherpad-lite/var
      - ./apps/etherpad/settings.json:/opt/etherpad-lite/settings.json
    ports:
      - "9001:9001"
    restart: always
    networks:
      - lulifa-next-admin

volumes:
  etherpad_data:

networks:
  lulifa-next-admin:
    name: lulifa-next-admin
    driver: bridge